---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAgMmIK29La12UDhrNq8T8NMJZmEBajQnnBKIOkU+EWvbghClUs5HdzpjEONWdihgAzZbwvpkbPd83krxe14MQFZoyBsXLeZZPPeqDfM81JaIbZPcvYDO8k1HxgBOtTC0br7tzzy6FS9ZTyAapB5y87LFc6dRfZA3j5XTW1EOgAkMIBsj/ZHUfr9uhg8d9gje86EJGZcZ8hr7TWNvK+ZjpZ0V7Nbqh55YkH0FwUGNrI2GM5FxL1JpwjrRjYJs42YnTveSCGQpNikn0Npy+DnLCd4aOnmRpyCI+yaz8G3cZxgqev9UZwFlOS8wVPu4o6O8z51KicPdQFhRYTb2V7FK/Q/BQfP/BShpx/P8pvVtDKjauHhef+9wN7edaFUZioec4itk2+iPyMuO9suwf2StN12X+adEVHst2VNP2p30PYNKkJGtb9bp39mxzXAA3xJ4D+fE0GqI6lr37shZ3HaEY1s6Qoh7rv8J4+7TMf17lNhs90pb+l45ek/r+0Jo83C218dcPwKhoDn2GtaSwtuNyBcgCUEsuEBeJbXBWSMRs8/GUFFTOjLSkBakKsP35P0+iwYv27hf0TdFilhlEgJCvZ9K+NPWk7kXrDe5TtPVnmOyZgY51lIhp6j6i1EuRXtnEnF+O5cy0TOtYOzxf2rLeomRnnNZOP4sJzEDS2LYkoVhyKkQFG8YDbajbsCsO5ulxnXMk6bvPCb1Iq5YwsnO/RR5dy8WrJwOMt6/SWRWasvel8QasdLM93Iu/6HsR2KnoRMDirB1c6PTpWiSGJMQ0IeDQUIECzVtDcOcWxfg5upLokHKQn0n45y1sajtsdtYxa+M3tfVbFb4HiBvQ1XIjwmboRkDbApwiHadSna3zMPlcHczwXFLYwTJRSI4eYhT1JmSpUg+kV6/jbNfS8ZSHk5A==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
